# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('recent_view_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recent_edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Category')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='DraftComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('recent_edit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Category')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRespond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respond_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Option')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Vote')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Vote'),
        ),
    ]
