# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('nick_name', models.CharField(default='', max_length=50)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.CharField(default='', max_length=100)),
                ('company', models.CharField(default='', max_length=100)),
                ('major', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('google_uid', models.CharField(default='', max_length=100)),
                ('facebook_uid', models.CharField(default='', max_length=100)),
                ('naver_uid', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Query')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='member_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.MemberStatus'),
        ),
    ]
