# Generated by Django 2.0.2 on 2018-04-19 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180418_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth',
            field=models.DateField(default=datetime.datetime(1992, 1, 1, 0, 0)),
        ),
    ]
