# Generated by Django 2.0.2 on 2018-04-18 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 28, 8, 33, 23, 590794, tzinfo=utc)),
        ),
    ]
