# Generated by Django 2.0.2 on 2018-04-19 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180418_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 7, 23, 59, 216990, tzinfo=utc)),
        ),
    ]
