# Generated by Django 2.0.2 on 2018-04-23 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180423_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 8, 55, 40, 550394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
