# Generated by Django 2.0.2 on 2018-05-18 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20180423_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 4, 9, 1, 200807, tzinfo=utc)),
        ),
    ]
