# Generated by Django 2.0.2 on 2018-05-20 16:23

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20180518_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=survey.models.get_end_date),
        ),
    ]
